# fly.toml app configuration file generated for mslu-timetable on 2025-02-27T18:39:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mslu-timetable'
primary_region = 'fra'

[build]

[env]
  ORIGIN = "https://timetable.of.by"

[build.args]
  MSLU_BACKEND_ENDPOINT = "http://schedule.mslu.by"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
