# Review deployment to next.timetable.of.by on every push to dev

name: Fly Deploy Dev
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Deploy review app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    environment:
      name: next
      url: https://next-mslu-timetable.fly.dev/
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set-up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy with next config
        run: flyctl deploy --remote-only --config fly.next.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
